package:
  name: cyrasterize
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools
    - numpy <2.0
    - cython >0.23
    - glew 2.*
    - glfw3 3.2.*
    - msinttypes r26  # [win]

  run:
    - python
    - numpy <2.0
    - glew 2.*
    - glfw3 3.2.*

about:
  home: https://github.com/menpo/cyrasterize/
  license: BSD
