package:
  name: cyrasterize
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.10,<2.0
    - cython >=0.23
    - glew 1.11.0
    - glfw3 3.0.4
    - msinttypes r26  # [win]

  run:
    - python
    - numpy >=1.10,<2.0
    - glew 1.11.0  # [unix]
    - glfw3 3.0.4  # [unix]

test:
  requires:
    - nose

  commands:
    - nosetests cyrasterize -v

about:
  home: https://github.com/menpo/cyrasterize
  license: BSD 3-clause
