package:
  name: cyrasterize
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cython
    - glew-osmesa
    - msinttypes r26  # [win]

  run:
    - python
    - numpy
    - glew-osmesa

about:
  home: https://github.com/menpo/cyrasterize/
  license: BSD
